# docker-compose.yml
version: '3'
services:
  subapp:
    container_name: subapp
    image: nginx
    ports:
      - 8090:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
